"""Add PlantImage table and update Plant

Revision ID: 78680eaae9a6
Revises: 30876e2472f9
Create Date: 2025-06-29 16:01:57.148531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78680eaae9a6'
down_revision = '30876e2472f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.drop_column('image_url2')
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('image_url2', sa.VARCHAR(length=200), nullable=True))

    # ### end Alembic commands ###
