"""Add scientific_surname to Plant

Revision ID: 85408a059b8b
Revises: 78680eaae9a6
Create Date: 2025-07-06 13:38:53.196515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85408a059b8b'
down_revision = '78680eaae9a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scientific_surname', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.drop_column('scientific_surname')

    # ### end Alembic commands ###
